---
title: "NC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
library(ncdf4)
library(ggplot2)
library(dplyr)
library(tidyr)

```{r}
nc <- nc_open("C:/Users/Nicole/Desktop/ADC2018/Data/WG2013CTD.nc")

```

```{r}

print(nc)
```

```{r}
vars <- attributes(nc$var)$names
vars
```

```{r}
dims <- attributes(nc$dim)$names
dims
```

```{r}
salinity <- ncvar_get(nc, "sal")
time_mat <- ncvar_get(nc, "time")
depth <- ncvar_get(nc, "z")
```


#reformat the output
matlab time to r added tie to salinity
```{r}
time <- as.POSIXct((time_mat + 719529)*86400, origin = "1970-01-01", tz = "UTC")
```

```{r}
salinity_data <- as.data.frame(salinity) 
```
assign column names to depth values

```{r}
names(salinity_data) <- as.character(depth) 
```
reshape the name and time

make a long data with gather
so we are ignoring time
```{r}
salinity_data_long <- salinity_data %>% 
    mutate(time = time) %>% 
    gather(key = "depth", value = "salinity", -time) %>% 
    mutate(depth = as.numeric(depth)) %>% 
    arrange(time)
head(salinity_data_long)
```


```{r}
ggplot(salinity_data_long, mapping = aes(x = time, y = depth, fill = salinity)) +
    geom_raster() +
    theme_bw() +
    ylab("Depth (m)") +
    xlab("") +
    scale_fill_continuous(low = "gray", high = "red", name = "Salinity (psu)")
```


```{r}
ggplot(salinity_data_long, mapping = aes(x = salinity,
                                        y = depth,
                                        color = time,
                                        group = time))+
  geom_line(size=0.1) +
  scale_y_reverse()
```


