---
title: "noaa"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

```{r}
#install.packages("rnoaa")
#install.packages("ncd4")
#install.packages("ggplot2")
library(rnoaa)
library(ncdf4)
library(ggplot2)
```
Read in buoy data

```{r}
bd <- buoy(dataset = "cwind", buoyid = 46080, year = 2018, datatype = "c")
```

```{r}
wind_speed <- data.frame(time = as.POSIXct(bd$date$time), 
                         speed = bd$data$wind_spd)
```

```{r}
ggplot(wind_speed, aes(c = time, y = speed)) +
geom_point()
```

```{r}
bd <- buoy(dataset = 'cwind', buoyid = 46080, year = 2018, datatype = "c")

wind_speed <- data.frame(time = as.POSIXct(bd$data$time), speed = bd$data$wind_spd, stringsAsFactors = F)
```

```{r}
ggplot(wind_speed, aes(x = time, y = speed)) + 
    geom_point() +
    xlab("") +
    ylab("Wind Speed (m/s)") +
    ggtitle("2018 NOAA buoy observations near Kodiak, AK") +
    theme_bw()
```

```{r}
install.packages("mapr", dependencies = TRUE) # run once
```

```{r}
library(mapr)
library(spocc)
```

```{r}
spp <- c('Ursus arctos', 'Ursus maritimus')
dat <- occ(query = spp, from = 'gbif', has_coords = TRUE, limit = 500)
```

```{r}
map_leaflet(dat, size = 1, color = c("brown", "gray"), alpha = 1)
```
